[2024-04-16 20:43:25,732][root][INFO] - Command line args:

[2024-04-16 20:43:25,732][root][INFO] - Hydra and wandb output path: /Users/ajgeorge/python/sis/logs/2024-04-16/20-43-25
[2024-04-16 20:43:25,732][root][INFO] - Solver output path: /Users/ajgeorge/python/sis/logs/2024-04-16/20-43-25
[2024-04-16 20:43:33,834][root][INFO] - ---------------------------------------------------------------
[2024-04-16 20:43:33,837][root][INFO] - Run config:
wandb:
  project: sis
  resume: allow
  mode: run
  name: 2024-04-16/20-43-25,
  tags: []
  id: dc87bf1e4cb1d0adf5e8999e4663a43abc3e0b10fcbdb8c4381d6694c44ee800
keops_build_path: /Users/ajgeorge/.cache/keops/unknown/2024-04-16/20-43-25
merge_wandb_resume_cfg: true
restore_ckpt_from_wandb: true
target:
  _target_: stint_sampler.targets.targets.gmm
  d: 2
  mean: 5.0
  var: 0.3
interpolant:
  _target_: stint_sampler.stint.linearInterpolants.linear
  type: trig
model:
  _target_: stint_sampler.models.scoreNets.DISnet
  dim: 2
  width: 64
hjb_solver:
  _target_: stint_sampler.hjb_solver.oc.test
seed: 1
T: 1.0
dim: 2
eps0: 1.0e-05
eps1: 1.0e-05
batch_size: 128
log_interval: 10
eval_interval: 100
jit_lossFn: 1
train:
  NtTrain: 100
  epochs: 2000
  epoch_steps: 4
  learning_rate: 0.01
solver:
  _target_: stint_sampler.stint.sis.half_sis
sampler:
  Nsamples: 10000
  NtSampler: 1000
pde_solver:
  scale_init_train: 0.01
eval:
  hist_dims:
  - 0
  - 1
out_dir: /Users/ajgeorge/python/sis/logs/2024-04-16/20-43-25

[2024-04-16 20:43:33,837][root][INFO] - ---------------------------------------------------------------
[2024-04-16 20:43:34,326][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-16 20:43:34,327][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-16 20:43:34,330][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/jaxlib/../../../libtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
[2024-04-16 20:43:34,483][root][INFO] - Checkpoint directory: /Users/ajgeorge/python/sis/logs/2024-04-16/20-43-25/ckpt
[2024-04-16 20:43:39,730][root][CRITICAL] - Error in call to target 'stint_sampler.stint.sis.half_sis':
InstantiationException('Error in call to target \'stint_sampler.models.scoreNets.DISnet\':\nTypeError("DISnet.__init__() missing 1 required positional argument: \'target_score\'")\nfull_key: hjb_solver.cfg.model')
full_key: solver
Traceback (most recent call last):
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/flax/linen/kw_only_dataclasses.py", line 233, in init_wrapper
    dataclass_init(self, *args, **kwargs)
TypeError: DISnet.__init__() missing 1 required positional argument: 'target_score'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/python/sis/stint_sampler/stint/sis.py", line 165, in __init__
    self.hjb_solver = instantiate(self.cfg.hjb_solver,cfg=self.cfg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 366, in instantiate_node
    cfg[key] = instantiate_node(
               ^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'stint_sampler.models.scoreNets.DISnet':
TypeError("DISnet.__init__() missing 1 required positional argument: 'target_score'")
full_key: hjb_solver.cfg.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ajgeorge/python/sis/main.py", line 72, in main
    sampler = instantiate(cfg.solver, cfg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'stint_sampler.stint.sis.half_sis':
InstantiationException('Error in call to target \'stint_sampler.models.scoreNets.DISnet\':\nTypeError("DISnet.__init__() missing 1 required positional argument: \'target_score\'")\nfull_key: hjb_solver.cfg.model')
full_key: solver
