[2024-04-15 10:47:46,118][root][INFO] - Command line args:

[2024-04-15 10:47:46,118][root][INFO] - Hydra and wandb output path: /Users/ajgeorge/python/sis/logs/2024-04-15/10-47-46
[2024-04-15 10:47:46,118][root][INFO] - Solver output path: /Users/ajgeorge/python/sis/logs/2024-04-15/10-47-46
[2024-04-15 10:47:52,905][root][INFO] - ---------------------------------------------------------------
[2024-04-15 10:47:52,907][root][INFO] - Run config:
wandb:
  project: sis
  resume: allow
  mode: run
  name: 2024-04-15/10-47-46,
  tags: []
  id: 6eb95a3330eb52d5812b4dc87179a79ec7ba3d0d28b18eb2684b1b647a1a33a0
keops_build_path: /Users/ajgeorge/.cache/keops/unknown/2024-04-15/10-47-46
merge_wandb_resume_cfg: true
restore_ckpt_from_wandb: true
target:
  _target_: stint_sampler.targets.targets.gmm
  mean: 5.0
  var: 1.0
interpolant:
  _target_: stint_sampler.stint.linearInterpolants.linear
  type: sin
model:
  _target_: stint_sampler.models.scoreNets.DenseNet
  dim: 2
  features:
  - 20
  - 50
  - 200
  - 200
  - 50
seed: 1
T: 1.0
dim: 2
eps0: 1.0e-05
eps1: 1.0e-05
batch_size: 128
train:
  NtTrain: 10
  epochs: 1000
  epoch_steps: 4
  learning_rate: 0.01
solver:
  _target_: stint_sampler.stint.sis.half_sis
sampler:
  Nsamples: 10000
  NtSampler: 1000
out_dir: /Users/ajgeorge/python/sis/logs/2024-04-15/10-47-46

[2024-04-15 10:47:52,907][root][INFO] - ---------------------------------------------------------------
[2024-04-15 10:47:53,550][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 10:47:53,550][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 10:47:53,551][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/jaxlib/../../../libtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
[2024-04-15 10:47:53,568][root][INFO] - Checkpoint directory: /Users/ajgeorge/python/sis/logs/2024-04-15/10-47-46/ckpt
[2024-04-15 10:48:48,127][root][CRITICAL] - 'method' object is not subscriptable
Traceback (most recent call last):
  File "/Users/ajgeorge/python/sis/main.py", line 77, in main
    plotObj.make_hist_plot(ax)
  File "/Users/ajgeorge/python/sis/stint_sampler/eval/plotter.py", line 12, in make_hist_plot
    vals, xedges, yedges = np.histogram2d(self.data[:, 0],self.data[:, 1], 40)
                                          ~~~~~~~~~^^^^^^
TypeError: 'method' object is not subscriptable
