{'wandb': {'project': 'sis', 'resume': 'allow', 'mode': 'run', 'name': '2024-04-15/09-52-55,', 'tags': [], 'id': '241d38acdf8f6eab7378f7f3d998a358d40f1604de58f82edb829c5ccb45d231'}, 'keops_build_path': '/Users/ajgeorge/.cache/keops/unknown/2024-04-15/09-52-55', 'merge_wandb_resume_cfg': True, 'restore_ckpt_from_wandb': True, 'target': {'_target_': 'stint_sampler.targets.targets.gmm', 'mean': 5.0, 'var': 1.0}, 'interpolant': {'_target_': 'stint_sampler.stint.linearInterpolants.linear', 'type': 'sin'}, 'model': {'_target_': 'stint_sampler.models.scoreNets.DenseNet', 'dim': 2, 'features': [20, 50, 200, 200, 50]}, 'seed': 1, 'T': 1.0, 'dim': 2, 'batch_size': 128, 'NtTrain': 100, 'epochs': 1000, 'epoch_steps': 4, 'learning_rate': 0.01, 'solver': {'_target_': 'stint_sampler.stint.sis.half_sis'}, 'sampler': {'Nsamples': 10000, 'NtSampler': 1000}, 'out_dir': '/Users/ajgeorge/python/sis/logs/2024-04-15/09-52-55'}
[2024-04-15 09:53:02,448][root][INFO] - ---------------------------------------------------------------
[2024-04-15 09:53:02,450][root][INFO] - Run config:
wandb:
  project: sis
  resume: allow
  mode: run
  name: 2024-04-15/09-52-55,
  tags: []
  id: 241d38acdf8f6eab7378f7f3d998a358d40f1604de58f82edb829c5ccb45d231
keops_build_path: /Users/ajgeorge/.cache/keops/unknown/2024-04-15/09-52-55
merge_wandb_resume_cfg: true
restore_ckpt_from_wandb: true
target:
  _target_: stint_sampler.targets.targets.gmm
  mean: 5.0
  var: 1.0
interpolant:
  _target_: stint_sampler.stint.linearInterpolants.linear
  type: sin
model:
  _target_: stint_sampler.models.scoreNets.DenseNet
  dim: 2
  features:
  - 20
  - 50
  - 200
  - 200
  - 50
seed: 1
T: 1.0
dim: 2
batch_size: 128
NtTrain: 100
epochs: 1000
epoch_steps: 4
learning_rate: 0.01
solver:
  _target_: stint_sampler.stint.sis.half_sis
sampler:
  Nsamples: 10000
  NtSampler: 1000
out_dir: /Users/ajgeorge/python/sis/logs/2024-04-15/09-52-55
[2024-04-15 09:53:02,450][root][INFO] - ---------------------------------------------------------------
[2024-04-15 09:53:03,261][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 09:53:03,261][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 09:53:03,263][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/jaxlib/../../../libtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
[2024-04-15 09:53:03,387][root][INFO] - Checkpoint directory: /Users/ajgeorge/python/sis/logs/2024-04-15/09-52-55/ckpt
[2024-04-15 09:53:07,462][root][CRITICAL] - Error in call to target 'stint_sampler.stint.sis.half_sis':
AttributeError("'half_sis' object has no attribute 'k'")
full_key: solver
Traceback (most recent call last):
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/python/sis/stint_sampler/stint/sis.py", line 113, in __init__
    k1, self.k = random.split(self.k)
                              ^^^^^^
AttributeError: 'half_sis' object has no attribute 'k'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/ajgeorge/python/sis/main.py", line 72, in main
    sampler = instantiate(cfg.solver, cfg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'stint_sampler.stint.sis.half_sis':
AttributeError("'half_sis' object has no attribute 'k'")
full_key: solver